all:
  ice_backend:
    google_apps_domain: icepique.com
    default_image: icons/default.png

    god_auth:
      secret: "KMrJqQFx7fwceQper48CHPq4PaqBSQZq"
      timeout:  3600

  sf_twitter_bootstrap:
    web_dir:                      /sfTwitterBootstrapPlugin
    image_dir:                    /sfTwitterBootstrapPlugin/images/
    default_image:                config.png
    dashboard_url:                @homepage
    resize_mode:                  thumbnail
    site:                         My Site Name
    include_path:                 true
    include_assets:               true
    include_jquery:               true
    include_jquery_no_conflict:   false
    login_route:                  @sf_guard_signin
    logout:                       true
    logout_route:                 @sf_guard_signout
    top_link_to_fieldset:         true
    display_top_pagination:       true
    use_icons_in_button:          true
    breadcrumb_root_name:         Home
